LinkedList.LinkedList linkedList = new LinkedList.LinkedList();
linkedList.InsertLast(10);
linkedList.InsertLast(20);
linkedList.InsertLast(30);
linkedList.InsertLast(40);
var searchItem = linkedList.IndexOf(20);
linkedList.Print();
linkedList.Reverse();
linkedList.Print();
linkedList.RemoveLast();
linkedList.RemoveFirst();
var arr = linkedList.ConverttoArray();